branch-defaults:
  default:
    environment: travelbuddy-env
environment-defaults:
  Travelbuddy-env:
    branch: null
    repository: null
global:
  application_name: travelbuddy
  default_ec2_keyname: null
  default_platform: Tomcat 8.5 with Corretto 11 running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
